<?php

  $lang_array['graphit']['subtitle'] = 'This module allows you to create charts from data generated by your algorithms';

  $lang_array['graphit']['editor_edit_title'] = 'Modify Chart';
  $lang_array['graphit']['editor_create_title'] = 'Create a new Chart';

  $lang_array['app']['title_graphsettings'] = 'Change chart settings';
  $lang_array['app']['graph_refreshrate'] = 'Refresh Rate';
  $lang_array['app']['graph_refreshrate_expl'] = 'Indicates the time in seconds between 2 refreshs of the chart.';

  $lang_array['app']['graph_resolution'] = 'Resolution';
  $lang_array['app']['graph_resolution_expl'] = 'Indicates the chart\'s resolution';

  $lang_array['app']['graphcfg_behaviour'] = 'Behaviour';
  
  $lang_array['app']['graphcfg_ctype'] = 'Chart Type';
  $lang_array['app']['ctype_line'] = 'Line';
  $lang_array['app']['ctype_candle'] = 'Candlesticks';



?>