<?php

  $lang_array['graphit']['subtitle'] = 'This module allows you to create charts from data generated by your algorithms';

  $lang_array['graphit']['editor_edit_title'] = 'Modify Chart';
  $lang_array['graphit']['editor_create_title'] = 'Create a new Chart';

  $lang_array['app']['title_graphsettings'] = 'Change chart settings';
  $lang_array['app']['graph_refreshrate'] = 'Refresh Rate';
  $lang_array['app']['graph_refreshrate_expl'] = 'Indicates the time in seconds between 2 refreshs of the chart.';

  $lang_array['app']['graph_resolution'] = 'Resolution';
  $lang_array['app']['graph_resolution_expl'] = 'Indicates the chart\'s resolution';

  $lang_array['app']['graphcfg_behaviour'] = 'Behaviour';
  
  $lang_array['app']['graphcfg_ctype'] = 'Chart Type';
  $lang_array['app']['ctype_line'] = 'Line';
  $lang_array['app']['ctype_candle'] = 'Candlesticks';

  $lang_array['graphit']['name'] = 'Chart Name';
  $lang_array['graphit']['name_hint'] = 'Give your chart a name.';
  $lang_array['graphit']['refresh'] = 'Refresh Period';
  $lang_array['graphit']['refresh_hint'] = 'Indicate here the time (in seconds) period for which you want a chart refresh';

  $lang_array['graphit']['component_title'] = 'Chart Components';

  $lang_array['graphit']['tag_th']  = "Tag";
  $lang_array['graphit']['color_th'] = "Colour" ;
  $lang_array['graphit']['type_th'] = "Type";
  $lang_array['graphit']['query_th'] = "Query" ;
  $lang_array['graphit']['action_th'] = "Action" ;

  $lang_array['app']['add'] = 'Add';
  $lang_array['app']['del'] = 'Delete';


?>