<?php

  $lang_array['coredumps']['subtitle'] = "Visualize the core dumps generated by the quotek Robot in case of critical error.";
  $lang_array['coredumps']['cdlist'] = "Dumps List";
  $lang_array['coredumps']['content'] = 'Content';
  $lang_array['coredumps']['dumpfrom'] = 'Dump from';

?>